### ISSUE TITLE
Remote ISO Url Update

### ISSUE THREAD

**Issue by TheComputerDan** [brantleyp1/packer-image-builder#1]
The ISO Url now leads to a 404. Shown below are the old, and the new locations of the iso: 
* Old: https://cdimage.ubuntu.com/ubuntu-server/daily-live/current/jammy-live-server-amd64.iso
* New: https://cdimage.ubuntu.com/ubuntu-server/jammy/daily-live/current/jammy-live-server-amd64.iso

**Comment by brantleyp1** [comment]
I don't have the code for 22.04, though I have built it outside this repo and it wouldn't take much. I wouldn't recommend the dailies though since the checksum would change. I have a local copy of 20.04.2 for example that isn't the newest release, but part of the build does updates so you wind up in the same place without having to change the code very often.
